version: '3.5'

services:

  mysql:
    image: mysql
    container_name: mysql_mspatient
    environment:
      MYSQL_DATABASE: mspatient
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: 1gwUrfkG6GondXgc0mhC
      MYSQL_USERNAME : root
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

    ports:
      - 3308:3306
    volumes:
      - mysql_db:/data/db




volumes:

  mysql_db: